[2023-04-23 17:59:28,452] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 17:59:28] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 17:59:28,505] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 17:59:28] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 17:59:45,246] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 17:59:45] "POST /carro HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:00:16,347] WARNING add_carro() L57   Erro ao adicionar carro 'None','Honda','CIVIC','LQJ-9685', Carro com a mesma placa já cadastrado, verifique - call_trace=G:\Repositorios\MVP -- PUC\back-end\app.py L57  
[2023-04-23 18:00:16,347] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:00:16] "[31m[1mPOST /carro HTTP/1.1[0m" 409 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:00:31,550] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:00:31] "POST /carro HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:00:42,120] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:00:42] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:19,605] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.44:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,752] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,762] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,854] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,867] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,874] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:23,876] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:23] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,747] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,766] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,768] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,769] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,893] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:04:40,948] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:04:40] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:05:47,049] ERROR log_exception() L1449 Exception on /carro [GET] - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "G:\Repositorios\MVP -- PUC\back-end\app.py", line 93, in get_carro
    carro_id = query.id
AttributeError: 'CarroBuscaSchema' object has no attribute 'id'
[2023-04-23 18:05:47,054] INFO _log() L224  127.0.0.1 - - [23/Apr/2023 18:05:47] "[35m[1mGET /carro?marca=Honda&modelo=City&placa=LQJ-9685&ano=2019&quilometragem=100690 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:28,377] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.44:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,355] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,363] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,465] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,475] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,483] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:33,486] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:33] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:35,196] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:35] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:35,219] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:35] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-23 18:08:35,223] INFO _log() L224  192.168.0.44 - - [23/Apr/2023 18:08:35] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
